### ISSUE TITLE
User Story: I want to SEE (GET) all products so that I can decide what to buy / see

### ISSUE THREAD

**Issue by Kistinagrg** [mauve-monkeys/grace-shopper#11]
Implementation:
- [x] Backend - Set up APIs for all product GET request #25 
- [x] Backend - Create Product Model #24 
- [x] Frontend - Create a single product component #23
- [x] Frontend - Create an all products component #22
- [x] Frontend - Add a products property to the initial state of the store #27 
- [x] Products should have all (array of products) property 
- [x] Frontend - Create product sub-reducer #29
- [x] Frontend - Create an action type & action creator for displaying all products #29
- [x] Frontend - Create a default image in public #30
