### ISSUE TITLE
User Story: As a shopper, I want to be able to VIEW (GET) my cart on a product so I can see if I have everything I want

### ISSUE THREAD

**Issue by ctakemoto** [mauve-monkeys/grace-shopper#2]
Sub-tasks:
- [x] Backend - Create a many to many association with the User and Product tables with a through table called “cart” #10 
- [x] Frontend - Store the current products in the cart in the store #14
- [x] Frontend - create a cart sub-reducer #16
- [x] Frontend - action type and action creator to display cart items (from the store) #17
- [x] Front end - cart component - display (contingent on single product display) #18
