### ISSUE TITLE
User Story: As a shopper, I want to CLICK (GET) on a single product so I can get details on it.

### ISSUE THREAD

**Issue by MadelineEmde** [mauve-monkeys/grace-shopper#7]
Implementation: 
- [x] Backend -  Set up API endpoint for getting individual product details #9
- [x] Frontend - Create a product detail component #12
- [x] Frontend - Create product sub-reducer #13
- [x] Frontend - Create an action type & action creator for displaying product #15
